
SELECT ID_EMPLEADO, APELLIDOS_EMPLEADO,  $partition.FP_EMPLEADO(APELLIDOS_EMPLEADO)
AS particion FROM EMPLEADO;


SELECT ID_CLIENTE, APELLIDOS_CLIENTE,  $partition.FP_CLIENTE(APELLIDOS_CLIENTE)
AS particion FROM CLIENTE;


SELECT ID_INSUMO,FECHA_PEDIDO,  $partition.FP_PEDIDO(FECHA_PEDIDO)
AS particion FROM PEDIDO;



SELECT ID_ORDEN,  $partition.FP_ORDEN(FECHA_ORDEN)
AS particion FROM ORDEN;


SELECT ID_CLIENTE,FECHA_RESERVACION,  $partition.FP_RESERVACION(FECHA_RESERVACION)
AS particion FROM RESERVACION;



SELECT FORMA_PAGO,FECHA_FACTURA,  $partition.FP_FACTURA(FECHA_FACTURA)
AS particion FROM FACTURA;
