CREATE DATABASE RESTAURANTE_BD
ON PRIMARY(
NAME = 'Restaurante_Datos', FILENAME = 'C:\RESTAURANTE\DATOS\Primary.mdf',
SIZE = 5GB, MAXSIZE = 10GB, FILEGROWTH=25%
)
LOG ON(
NAME = 'Resaturante_Log', FILENAME = 'C:\RESTAURANTE\LOG\DatosLog.ldf',
SIZE = 5GB, MAXSIZE = 10GB, FILEGROWTH=25%
);

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP empleado_1;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP empleado_2;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP empleado_3;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP registro;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP mesa;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP proveedor;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP insumo;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP pedido_1;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP pedido_2;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP pedido_3;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP producto;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP combo;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP orden_1;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP orden_2;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP orden_3;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP orden_producto;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP orden_combo;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP cliente_1;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP cliente_2;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP cliente_3;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP reservacion_1;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP reservacion_2;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP reservacion_3;

ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP factura_1;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP factura_2;
ALTER DATABASE RESTAURANTE_BD
ADD FILEGROUP factura_3;


----ALTER DATABASE RESTAURANTE_BD
----ADD FILEGROUP transacciones;


-----------------------------------


ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'empleado_1', FILENAME = 'C:\RESTAURANTE\DATOS\empleados_1.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP empleado_1;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'empleado_2', FILENAME = 'C:\RESTAURANTE\DATOS\empleados_2.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP empleado_2;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'empleado_3', FILENAME = 'C:\RESTAURANTE\DATOS\empleados_3.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP empleado_3;




ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'registro', FILENAME = 'C:\RESTAURANTE\DATOS\registro.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP registro;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'mesa', FILENAME = 'C:\RESTAURANTE\DATOS\mesa.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP mesa;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'proveedor', FILENAME = 'C:\RESTAURANTE\DATOS\proveedor.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP proveedor;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'insumo', FILENAME = 'C:\RESTAURANTE\DATOS\insumo.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP insumo;




ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'pedido_1', FILENAME = 'C:\RESTAURANTE\DATOS\pedido_1.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP pedido_1;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'pedido_2', FILENAME = 'C:\RESTAURANTE\DATOS\pedido_2.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP pedido_2;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'pedido_3', FILENAME = 'C:\RESTAURANTE\DATOS\pedido_3.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP pedido_3;




ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'producto', FILENAME = 'C:\RESTAURANTE\DATOS\producto.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP producto;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'combo', FILENAME = 'C:\RESTAURANTE\DATOS\combo.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP combo;




ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'orden_1', FILENAME = 'C:\RESTAURANTE\DATOS\orden_1.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP orden_1;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'orden_2', FILENAME = 'C:\RESTAURANTE\DATOS\orden_2.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP orden_2;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'orden_3', FILENAME = 'C:\RESTAURANTE\DATOS\orden_3.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP orden_3;




ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'orden_producto', FILENAME = 'C:\RESTAURANTE\DATOS\orden_producto.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP orden_producto;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'orden_combo', FILENAME = 'C:\RESTAURANTE\DATOS\orden_combo.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP orden_combo;



ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'cliente_1', FILENAME = 'C:\RESTAURANTE\DATOS\cliente_1.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP cliente_1;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'cliente_2', FILENAME = 'C:\RESTAURANTE\DATOS\cliente_2.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP cliente_2;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'cliente_3', FILENAME = 'C:\RESTAURANTE\DATOS\cliente_3.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP cliente_3;




ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'reservacion_1', FILENAME = 'C:\RESTAURANTE\DATOS\reservacion_1.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP reservacion_1;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'reservacion_2', FILENAME = 'C:\RESTAURANTE\DATOS\reservacion_2.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP reservacion_2;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'reservacion_3', FILENAME = 'C:\RESTAURANTE\DATOS\reservacion_3.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP reservacion_3;






ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'factura_1', FILENAME = 'C:\RESTAURANTE\DATOS\factura_1.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP factura_1;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'factura_2', FILENAME = 'C:\RESTAURANTE\DATOS\factura_2.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP factura_2;

ALTER DATABASE RESTAURANTE_BD
ADD FILE(
NAME = 'factura_3', FILENAME = 'C:\RESTAURANTE\DATOS\factura_3.ndf',
SIZE=1GB, MAXSIZE=10GB, FILEGROWTH=25%
) TO FILEGROUP factura_3;




---Para comprobar
sp_helpdb[RESTAURANTE_BD];