---Usar BD
USE RESTAURANTE_BD;


CREATE TABLE SUCURSAL(
    ID_SUCURSAL VARCHAR(5) NOT NULL,
    NOMBRE_SUCURSAL VARCHAR(45) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    TELEFONO_SUCURSAL VARCHAR(9) NOT NULL,
    SALDO NUMERIC(10,2) NOT NULL,
    ID_SUCURSAL_CARGO VARCHAR(5) NOT NULL,

    CONSTRAINT PK_SUCURSAL PRIMARY KEY(ID_SUCURSAL),

    CONSTRAINT FK1_SUCURSAL FOREIGN KEY (ID_SUCURSAL_CARGO)
        REFERENCES SUCURSAL (ID_SUCURSAL)
) ON [PRIMARY];

--------------

CREATE TABLE CARGO(
    ID_CARGO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_CARGO VARCHAR(45) NOT NULL,

    CONSTRAINT PK_CARGO PRIMARY KEY(ID_CARGO)
)ON [PRIMARY];


CREATE NONCLUSTERED INDEX IDX_CARGO
ON CARGO (NOMBRE_CARGO);

-------------------

CREATE TABLE EMPLEADO_CODIGO(
    ID_EMPLEADO VARCHAR(8) NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,

    CONSTRAINT PK_EMPLEADO_CODIGO PRIMARY KEY(ID_EMPLEADO),

    CONSTRAINT FK1_EMPLEADO_CODIGO FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON [PRIMARY];

CREATE TABLE EMPLEADO(
    ID_EMPLEADO VARCHAR(8) NOT NULL,
    NOMBRES_EMPLEADO VARCHAR(45) NOT NULL,
    APELLIDOS_EMPLEADO VARCHAR(45) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    TELEFONO_EMPLEADO VARCHAR(9) NULL,
    NACIMIENTO DATE NOT NULL,
    CORREO VARCHAR(45) NULL,
    SALARIO NUMERIC(6,2) NOT NULL,

    ID_CARGO INT NOT NULL,

    CONSTRAINT FK3_EMPLEADO FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO_CODIGO (ID_EMPLEADO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK2_EMPLEADO FOREIGN KEY (ID_CARGO)
        REFERENCES CARGO (ID_CARGO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
) ON EP_EMPLEADO(APELLIDOS_EMPLEADO);


 CREATE NONCLUSTERED INDEX IDX_EMPLE
 ON EMPLEADO(APELLIDOS_EMPLEADO)
 INCLUDE (ID_EMPLEADO)
 ON EP_EMPLEADO(APELLIDOS_EMPLEADO);

CREATE NONCLUSTERED INDEX IDX2_EMPLE 
ON EMPLEADO (NOMBRES_EMPLEADO);


--------------------------------------


CREATE TABLE REGISTRO_JORNADA(
    HORA_ENTRADA DATETIME NOT NULL,
    HORA_SALIDA DATETIME NULL,

    ID_EMPLEADO VARCHAR(8) NOT NULL,

    CONSTRAINT PK_REGISTRO_JORNADA PRIMARY KEY(ID_EMPLEADO,HORA_ENTRADA),

    CONSTRAINT FK1_REGISTRO_JORNADA FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO_CODIGO (ID_EMPLEADO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON  registro;


CREATE NONCLUSTERED INDEX IDX_RJ 
ON REGISTRO_JORNADA (ID_EMPLEADO);



--------------------------------------


CREATE TABLE MESA(
    ID_MESA INT IDENTITY(1,1) NOT NULL,
    ESTADO BIT DEFAULT 0,
    CAPACIDAD INT NOT NULL,

    ID_SUCURSAL VARCHAR(5) NOT NULL, 

    CONSTRAINT PK_MESA PRIMARY KEY(ID_MESA, ID_SUCURSAL),

    CONSTRAINT FK1_MESA FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
) ON mesa;


CREATE NONCLUSTERED INDEX IDX_MESA 
ON MESA (ESTADO);



--------------------------------------



CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(45) NULL,
    NOMBRE_EMPRESA VARCHAR(45) NOT NULL,
    TELEFONO_PROVEEDOR VARCHAR(9) NULL,

    CONSTRAINT PK_PROVEEDOR PRIMARY KEY(ID_PROVEEDOR)
) ON proveedor;


CREATE NONCLUSTERED INDEX IDX_PROVEEDOR
ON PROVEEDOR (NOMBRE_PROVEEDOR);
CREATE NONCLUSTERED INDEX IDX2_PROVEEDOR
ON PROVEEDOR (NOMBRE_EMPRESA);



--------------------------------------


CREATE TABLE TIPO_INSUMO(
    ID_TIPO_INSUMO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_TIPO_INSUMO VARCHAR(45) NOT NULL,

    CONSTRAINT PK_TIPO_INSUMO PRIMARY KEY(ID_TIPO_INSUMO)
) ON [PRIMARY];


CREATE NONCLUSTERED INDEX IDX_TIPO_INSUMO
ON TIPO_INSUMO (NOMBRE_TIPO_INSUMO);


--------------------------------------


CREATE TABLE INSUMO(
    ID_INSUMO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_INSUMO VARCHAR(45) NOT NULL,
    MARCA VARCHAR(45) NULL,

    ID_PROVEEDOR INT NOT NULL,
    ID_TIPO_INSUMO INT NOT NULL,

    CONSTRAINT PK_INSUMO PRIMARY KEY(ID_INSUMO),

    CONSTRAINT FK1_INSUMO FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES PROVEEDOR (ID_PROVEEDOR)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK2_INSUMO FOREIGN KEY (ID_TIPO_INSUMO)
        REFERENCES TIPO_INSUMO (ID_TIPO_INSUMO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
) ON insumo;


CREATE NONCLUSTERED INDEX IDX_INSUMO
ON INSUMO (NOMBRE_INSUMO);


--------------------------------------

CREATE TABLE PEDIDO(
    FECHA_PEDIDO DATETIME NOT NULL,
    CANTIDAD_PEDIDO INT NOT NULL,
    OBSERVACIONES VARCHAR(100) NULL,

    PRECIO_INSUMO NUMERIC(6,2) NOT NULL,
    CANTIDAD_INSUMO INT NOT NULL,
    MEDIDA_INSUMO VARCHAR(5) NULL,

    ID_SUCURSAL VARCHAR(5) NOT NULL,
    ID_INSUMO INT NOT NULL,

    CONSTRAINT FK1_PEDIDO FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK2_PEDIDO FOREIGN KEY (ID_INSUMO)
        REFERENCES INSUMO (ID_INSUMO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
) ON EP_PEDIDO(FECHA_PEDIDO);

 CREATE NONCLUSTERED INDEX IDX_PEDIDO
 ON PEDIDO(FECHA_PEDIDO)
 INCLUDE (ID_INSUMO)
 ON EP_PEDIDO(FECHA_PEDIDO);



--------------------------------------


CREATE TABLE TIPO_PRODUCTO(
    ID_TIPO_PRODUCTO INT IDENTITY(1,1)  NOT NULL,
    NOMBRE_TIPO_PRODUCTO VARCHAR(45) NOT NULL,
    
    CONSTRAINT PK_TIPO_PRODUCTO PRIMARY KEY(ID_TIPO_PRODUCTO),
) ON [PRIMARY];


--------------------------------------


CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(45) NOT NULL,
    PRECIO_PRODUCTO NUMERIC(5,2) NOT NULL,
    DESCRIPCION VARCHAR(200) NULL,

    ID_TIPO_PRODUCTO INT NOT NULL,

    CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO),

    CONSTRAINT FK1_PRODUCTO FOREIGN KEY (ID_TIPO_PRODUCTO)
        REFERENCES TIPO_PRODUCTO (ID_TIPO_PRODUCTO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
) ON producto;

CREATE NONCLUSTERED INDEX IDX_PRODUCTO
ON PRODUCTO (NOMBRE_PRODUCTO);

CREATE NONCLUSTERED INDEX IDX2_PRODUCTO
ON PRODUCTO (ID_TIPO_PRODUCTO);


--------------------------------------


CREATE TABLE TIPO_COMBO(
    ID_TIPO_COMBO INT IDENTITY(1,1)  NOT NULL,
    NOMBRE_TIPO_COMBO VARCHAR(45) NOT NULl,

    CONSTRAINT PK_TIPO_COMBO PRIMARY KEY(ID_TIPO_COMBO)
) ON [PRIMARY];


--------------------------------------

CREATE TABLE COMBO(
    ID_COMBO INT IDENTITY(1,1) NOT NULL,
    NOMBRE_COMBO VARCHAR(45) NOT NULL,
    PRECIO_COMBO NUMERIC(6,2) NOT NULL,

    ID_TIPO_COMBO INT NOT NULL,

    CONSTRAINT PK_COMBO PRIMARY KEY(ID_COMBO),

    CONSTRAINT FK1_COMBO FOREIGN KEY (ID_TIPO_COMBO)
        REFERENCES TIPO_COMBO (ID_TIPO_COMBO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
) ON combo;

CREATE NONCLUSTERED INDEX IDX_COMBO
ON COMBO (NOMBRE_COMBO);

CREATE NONCLUSTERED INDEX IDX2_COMBO
ON COMBO (ID_TIPO_COMBO);


--------------------------------------

CREATE TABLE PROD_COMBO(
    ID_COMBO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CANTIDAD INT NOT NULL,

    CONSTRAINT PK_PROD_COMBO PRIMARY KEY(ID_COMBO, ID_PRODUCTO),

    CONSTRAINT FK1_PROD_COMBO FOREIGN KEY (ID_COMBO)
        REFERENCES COMBO (ID_COMBO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_PROD_COMBO FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO (ID_PRODUCTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON combo;


--------------------------------------

CREATE TABLE ORDEN_CODIGO(
    ID_ORDEN INT IDENTITY(1,1) NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,

    CONSTRAINT PK_ORDEN_CODIGO PRIMARY KEY(ID_ORDEN, ID_SUCURSAL),

    CONSTRAINT FK1_ORDEN_CODIGO FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON [PRIMARY];


CREATE TABLE ORDEN(
    ID_ORDEN INT NOT NULL,
    FECHA_ORDEN DATETIME NOT NULL,

    ID_MESA INT NOT NULL,
    ID_EMPLEADO VARCHAR(8) NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,

    CONSTRAINT FK4_ORDEN FOREIGN KEY (ID_ORDEN,ID_SUCURSAL)
        REFERENCES ORDEN_CODIGO (ID_ORDEN, ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK1_ORDEN FOREIGN KEY (ID_MESA, ID_SUCURSAL)
        REFERENCES MESA (ID_MESA, ID_SUCURSAL),

    CONSTRAINT FK2_ORDEN FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO_CODIGO (ID_EMPLEADO)

) ON EP_ORDEN(FECHA_ORDEN);



 CREATE NONCLUSTERED INDEX IDX_ORDEN
 ON ORDEN(FECHA_ORDEN)
 INCLUDE (ID_ORDEN)
 ON EP_ORDEN(FECHA_ORDEN);


 CREATE NONCLUSTERED INDEX IDX2_ORDEN
ON ORDEN (ID_EMPLEADO);



--------------------------------------



CREATE TABLE ORD_PROD(
    CANTIDAD_PROD INT NOT NULL,

    ID_ORDEN INT NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,
    ID_PRODUCTO INT NOT NULL,

    TOTAL NUMERIC(6,2) NOT NULL,

    CONSTRAINT PK_ORD_PROD PRIMARY KEY(ID_ORDEN, ID_PRODUCTO),

    CONSTRAINT FK1_ORD_PROD FOREIGN KEY (ID_ORDEN, ID_SUCURSAL)
        REFERENCES ORDEN_CODIGO (ID_ORDEN, ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_ORD_PROD FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO (ID_PRODUCTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON orden_producto;



--------------------------------------



CREATE TABLE ORD_COMBO(
    CANTIDAD_COMB INT NOT NULL,

    ID_ORDEN INT NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,
    ID_COMBO INT NOT NULL,

    TOTAL NUMERIC(6,2) NOT NULL,

    CONSTRAINT PK_ORD_COMBO PRIMARY KEY(ID_ORDEN, ID_COMBO),

    CONSTRAINT FK1_ORD_COMBO FOREIGN KEY (ID_ORDEN, ID_SUCURSAL)
        REFERENCES ORDEN_CODIGO (ID_ORDEN, ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_ORD_COMBO FOREIGN KEY (ID_COMBO)
        REFERENCES COMBO (ID_COMBO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON orden_combo;


--------------------------------------


CREATE TABLE CLIENTE_CODIGO(
    ID_CLIENTE VARCHAR(8) NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,
    CONSTRAINT PK_CLIENTE_CODIGO PRIMARY KEY(ID_CLIENTE,ID_SUCURSAL),

    CONSTRAINT FK1_CLIENTE_CODIGO FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON [PRIMARY];


CREATE TABLE CLIENTE(
    ID_CLIENTE VARCHAR(8) NOT NULL,
    NOMBRES_CLIENTE VARCHAR(45) NOT NULL,
    APELLIDOS_CLIENTE VARCHAR(45) NULL,
    TELEFONO_CLIENTE VARCHAR(9) NOT NULL,

    ID_SUCURSAL VARCHAR(5) NOT NULL,

    CONSTRAINT FK1_CLIENTE FOREIGN KEY (ID_CLIENTE, ID_SUCURSAL)
        REFERENCES CLIENTE_CODIGO (ID_CLIENTE, ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ON EP_CLIENTE(APELLIDOS_CLIENTE);



 CREATE NONCLUSTERED INDEX IDX_CLIE
 ON CLIENTE(APELLIDOS_CLIENTE)
 INCLUDE (ID_CLIENTE)
 ON EP_CLIENTE(APELLIDOS_CLIENTE);

  CREATE NONCLUSTERED INDEX IDX2_CLIE
ON CLIENTE (NOMBRES_CLIENTE);


--------------------------------------

CREATE TABLE RESERVACION(
    FECHA_RESERVACION DATETIME NOT NULL,

    CONFIRMACION BIT DEFAULT 0,

    ID_CLIENTE VARCHAR(8) NOT NULL,
    ID_MESA INT NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,

    CONSTRAINT FK1_RESERVACION FOREIGN KEY (ID_CLIENTE,ID_SUCURSAL)
        REFERENCES CLIENTE_CODIGO (ID_CLIENTE, ID_SUCURSAL),

    CONSTRAINT FK2_RESERVACION FOREIGN KEY (ID_MESA, ID_SUCURSAL)
        REFERENCES MESA (ID_MESA, ID_SUCURSAL)
) ON EP_RESERVACION(FECHA_RESERVACION);


 CREATE NONCLUSTERED INDEX IDX_RESER
 ON RESERVACION(FECHA_RESERVACION)
 INCLUDE (ID_CLIENTE)
 ON EP_RESERVACION(FECHA_RESERVACION);

--------------------------------------

CREATE TABLE FACTURA(
    FECHA_FACTURA DATETIME NOT NULL,

    TOTAL NUMERIC(10,2) NOT NULL,
    IGV INT NOT NULL,
    FORMA_PAGO VARCHAR(45) NOT NULL,

    ID_MESA INT NOT NULL,
    ID_SUCURSAL VARCHAR(5) NOT NULL,

    CONSTRAINT FK1_FACTURA FOREIGN KEY (ID_MESA, ID_SUCURSAL)
        REFERENCES MESA (ID_MESA, ID_SUCURSAL)

) ON EP_FACTURA(FECHA_FACTURA);


 CREATE NONCLUSTERED INDEX IDX_FACTURA
 ON FACTURA(FECHA_FACTURA)
 INCLUDE (FORMA_PAGO)
 ON EP_FACTURA(FECHA_FACTURA);