CREATE DATABASE RESTAURANTE;
USE RESTAURANTE;

CREATE TABLE DISTRITO(
	ID_DISTRITO INT NOT NULL,
	NOMBRE_DISTRITO VARCHAR(45) NOT NULL,

	CONSTRAINT PK_DISTRITO PRIMARY KEY(ID_DISTRITO)
);


CREATE TABLE SUCURSAL(
    ID_SUCURSAL INT NOT NULL, 
    NOMBRE_SUCURSAL VARCHAR(45) NOT NULL,
    UBICACION VARCHAR(45) NOT NULL,
    TELEFONO_SUCURSAL INT NOT NULL,
    SALDO NUMERIC(10,2) NOT NULL,
    ID_SUCURSAL_CARGO INT NOT NULL,
    ID_DISTRITO INT NOT NULL,

    CONSTRAINT PK_SUCURSAL PRIMARY KEY(ID_SUCURSAL),

    CONSTRAINT FK1_SUCURSAL FOREIGN KEY (ID_SUCURSAL_CARGO)
        REFERENCES SUCURSAL (ID_SUCURSAL),
    CONSTRAINT FK2_SUCURSAL FOREIGN KEY (ID_DISTRITO)
        REFERENCES DISTRITO (ID_DISTRITO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

CREATE TABLE CARGO(
    ID_CARGO INT NOT NULL,
    NOMBRE_CARGO VARCHAR(45) NOT NULL,

    CONSTRAINT PK_CARGO PRIMARY KEY(ID_CARGO)
);

CREATE TABLE EMPLEADO(
    ID_EMPLEADO INT NOT NULL,
    NOMBRES_EMPLEADO VARCHAR(45) NOT  NULL,
    APELLIDOS_EMPLEADO VARCHAR(45) NOT NULL,
    DIRECCION VARCHAR(45) NOT NULL,
    TELEFONO_EMPLEADO INT NULL,
    NACIMIENTO DATETIME NOT NULL,
    CORREO VARCHAR(45) NULL,
    SALARIO NUMERIC(6,2) NOT NULL,

    ID_SUCURSAL INT NOT NULL,
    ID_CARGO INT NOT NULL,
    ID_DISTRITO INT NOT NULL,
    ID_JEFE INT NOT NULL,

    CONSTRAINT PK_EMPLEADO PRIMARY KEY(ID_EMPLEADO),

    CONSTRAINT FK1_EMPLEADO FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_EMPLEADO FOREIGN KEY (ID_CARGO)
        REFERENCES CARGO (ID_CARGO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK3_EMPLEADO FOREIGN KEY (ID_DISTRITO)
        REFERENCES DISTRITO (ID_DISTRITO),
    CONSTRAINT FK4_EMPLEADO FOREIGN KEY (ID_JEFE)
    	REFERENCES EMPLEADO (ID_EMPLEADO)
);

CREATE TABLE REGISTRO_JORNADA(
    HORA_ENTRADA DATETIME NOT NULL,
    HORA_SALIDA DATETIME NOT NULL,

    ID_EMPLEADO INT NOT NULL,

    CONSTRAINT PK_REGISTRO_JORNADA PRIMARY KEY(ID_EMPLEADO),

    CONSTRAINT FK1_REGISTRO_JORNADA FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO (ID_EMPLEADO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
);

CREATE TABLE MESA(
    ID_MESA INT NOT NULL,
    ESTADO BIT DEFAULT 0,
    CAPACIDAD INT NOT NULL,

    ID_SUCURSAL INT NOT NULL, 

    CONSTRAINT PK_MESA PRIMARY KEY(ID_MESA, ID_SUCURSAL),

    CONSTRAINT FK1_MESA FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR INT NOT NULL,
    NOMBRE_PROVEEDOR VARCHAR(45) NULL,
    NOMBRE_EMPRESA VARCHAR(45) NOT NULL,
    TELEFONO_PROVEEDOR INT NULL,

    CONSTRAINT PK_PROVEEDOR PRIMARY KEY(ID_PROVEEDOR)
);

CREATE TABLE CLASIFICACION(
	ID_CLASIFICACION INT NOT NULL,
	NOMBRE_CLASIFICACION VARCHAR(45) NOT NULL,

	CONSTRAINT PK_CLASIFICACION PRIMARY KEY(ID_CLASIFICACION)
);


CREATE TABLE INGREDIENTE(
    ID_INGREDIENTE INT NOT NULL,
    NOMBRE_INGREDIENTE VARCHAR(45) NOT NULL,
    MARCA VARCHAR(45) NULL,
    FECHA_VENCIMIENTO DATETIME NOT NULL,
    PRECIO_INGREDIENTE NUMERIC(6,2) NOT NULL,
    CANTIDAD_MEDIDA INT NOT NULL,
    MEDIDA VARCHAR(15) NOT NULL,

    ID_PROVEEDOR INT NOT NULL,
    ID_CLASIFICACION INT NOT NULL,

    CONSTRAINT PK_INGREDIENTE PRIMARY KEY(ID_INGREDIENTE),

    CONSTRAINT FK1_INGREDIENTE FOREIGN KEY (ID_PROVEEDOR)
        REFERENCES PROVEEDOR (ID_PROVEEDOR)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK2_INGREDIENTE FOREIGN KEY (ID_CLASIFICACION)
        REFERENCES CLASIFICACION (ID_CLASIFICACION)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE PEDIDO(
    ID_PEDIDO INT NOT NULL,
    FECHA_PEDIDO DATETIME NOT NULL,
    CANTIDAD INT NOT NULL,
    OBSERVACIONES VARCHAR(45) NULL,

    ID_SUCURSAL INT NOT NULL,
    ID_INGREDIENTE INT NOT NULL,

    CONSTRAINT PK_PEDIDO PRIMARY KEY(ID_PEDIDO,ID_INGREDIENTE),

    CONSTRAINT FK1_PEDIDO FOREIGN KEY (ID_SUCURSAL)
        REFERENCES SUCURSAL (ID_SUCURSAL)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_PEDIDO FOREIGN KEY (ID_INGREDIENTE)
        REFERENCES INGREDIENTE (ID_INGREDIENTE)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);

CREATE TABLE CATEGORIA(
    ID_CATEGORIA INT NOT NULL,
    NOMBRE_CATEGORIA VARCHAR(45) NOT NULL,

    CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(45) NOT NULL,
    PRECIO_PRODUCTO NUMERIC(6,2) NOT NULL,
    DESCRIPCION VARCHAR(45) NULL,

    ID_CATEGORIA INT NOT NULL,

    CONSTRAINT PK_PRODUCTO PRIMARY KEY(ID_PRODUCTO),

    CONSTRAINT FK1_PRODUCTO FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA (ID_CATEGORIA)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE INGRE_PROD(
    CANTIDAD FLOAT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    ID_INGREDIENTE INT NOT NULL,

    CONSTRAINT PK_INGRE_PROD PRIMARY KEY(ID_PRODUCTO, ID_INGREDIENTE),

    CONSTRAINT FK1_INGRE_PROD FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO (ID_PRODUCTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_INGRE_PROD FOREIGN KEY (ID_INGREDIENTE)
        REFERENCES INGREDIENTE (ID_INGREDIENTE)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE TIPO(
    ID_TIPO INT NOT NULL,
    NOMBRE_TIPO VARCHAR(45) NOT NULl,

    CONSTRAINT PK_TIPO PRIMARY KEY(ID_TIPO)
);


CREATE TABLE COMBO(
    ID_COMBO INT NOT NULL,
    NOMBRE_COMBO VARCHAR(45) NOT NULL,
    PRECIO_COMBO NUMERIC(6,2) NOT NULL,

    ID_TIPO INT NOT NULL,

    CONSTRAINT PK_COMBO PRIMARY KEY(ID_COMBO),

    CONSTRAINT FK1_COMBO FOREIGN KEY (ID_TIPO)
        REFERENCES TIPO (ID_TIPO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE PROD_COMBO(
    ID_COMBO INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,

    CONSTRAINT PK_PROD_COMBO PRIMARY KEY(ID_COMBO, ID_PRODUCTO),

    CONSTRAINT FK1_PROD_COMBO FOREIGN KEY (ID_COMBO)
        REFERENCES COMBO (ID_COMBO)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_PROD_COMBO FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO (ID_PRODUCTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ORDEN(
	ID_ORDEN INT NOT NULL,

	ID_MESA INT NOT NULL,
	ID_EMPLEADO INT NOT NULL,
	ID_SUCURSAL INT NOT NULL,

	CONSTRAINT PK_ORDEN PRIMARY KEY(ID_ORDEN),

	CONSTRAINT FK1_ORDEN FOREIGN KEY (ID_MESA,ID_SUCURSAL)
        REFERENCES MESA (ID_MESA,ID_SUCURSAL),
    CONSTRAINT FK2_ORDEN FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO (ID_EMPLEADO)
);

CREATE TABLE ORD_COMBO(
    ID_ORDEN INT NOT NULL,
    ID_COMBO INT NOT NULL,

    CONSTRAINT PK_ORD_COMBO PRIMARY KEY(ID_ORDEN, ID_COMBO),

    CONSTRAINT FK1_ORD_COMBO FOREIGN KEY (ID_ORDEN)
        REFERENCES ORDEN (ID_ORDEN)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_ORD_COMBO FOREIGN KEY (ID_COMBO)
        REFERENCES COMBO (ID_COMBO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ORD_PROD(
    ID_ORDEN INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,

    CONSTRAINT PK_ORD_PROD PRIMARY KEY(ID_ORDEN, ID_PRODUCTO),

    CONSTRAINT FK1_ORD_PROD FOREIGN KEY (ID_ORDEN)
        REFERENCES ORDEN (ID_ORDEN)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT FK2_ORD_PROD FOREIGN KEY (ID_PRODUCTO)
        REFERENCES PRODUCTO (ID_PRODUCTO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE CLIENTE(
    ID_CLIENTE INT NOT NULL,
    NOMBRES_CLIENTE VARCHAR(45) NOT NULL,
    APELLIDOS_CLIENTE VARCHAR(45) NULL,
    TELEFONO_CLIENTE INT NOT NULL,

    ID_DISTRITO INT NULL,

    CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE),

    CONSTRAINT FK1_CLIENTE FOREIGN KEY (ID_DISTRITO)
        REFERENCES DISTRITO (ID_DISTRITO)
);

CREATE TABLE RESERVACION(
    ID_RESERVACION INT NOT NULL,
    FECHA_RESERVACION DATETIME NOT NULL,

    ID_CLIENTE INT NOT NULL,
    ID_MESA INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,

    CONSTRAINT PK_RESERVACION PRIMARY KEY(ID_RESERVACION),

    CONSTRAINT FK1_RESERVACION FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT FK2_RESERVACION FOREIGN KEY (ID_MESA,ID_SUCURSAL)
        REFERENCES MESA (ID_MESA,ID_SUCURSAL)
);

CREATE TABLE FORMA_PAGO(
    ID_FORMA_PAGO INT NOT NULL,
    NOMBRE_FORMA_PAGO INT NOT NULL,

    CONSTRAINT PK_FORMA_PAGO PRIMARY KEY(ID_FORMA_PAGO)
);

CREATE TABLE FACTURA(
    ID_FACTURA INT NOT NULL,
    FECHA_FACTURA DATETIME NOT NULL,
    TOTAL NUMERIC(10,2) NOT NULL,
    IGV INT NOT NULL,

    ID_FORMA_PAGO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_ORDEN INT NOT NULL,

    CONSTRAINT PK_FACTURA PRIMARY KEY(ID_FACTURA,ID_FORMA_PAGO),

    CONSTRAINT FK1_FACTURA FOREIGN KEY (ID_FORMA_PAGO)
        REFERENCES FORMA_PAGO (ID_FORMA_PAGO),
    CONSTRAINT FK2_FACTURA FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT FK3_FACTURA FOREIGN KEY (ID_ORDEN)
    	REFERENCES ORDEN (ID_ORDEN)
);

CREATE TABLE BANCO(
    ID_BANCO INT NOT NULL,
    NOMBRE_BANCO VARCHAR(45) NOT NULL,

    CONSTRAINT PK_BANCO PRIMARY KEY(ID_BANCO)
);

CREATE TABLE TARJETA(
    ID_FORMA_PAGO INT NOT NULL,

    MONEDA VARCHAR(45) NOT NULL,
    NUMERO_TRANS INT NOT NULL,

    ID_BANCO INT NOT NULL,

    CONSTRAINT PK_TARJETA PRIMARY KEY(ID_FORMA_PAGO),

    CONSTRAINT FK1_TARJETA FOREIGN KEY (ID_FORMA_PAGO)
        REFERENCES FORMA_PAGO (ID_FORMA_PAGO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE,
    CONSTRAINT FK2_TARJETA FOREIGN KEY (ID_BANCO)
        REFERENCES BANCO (ID_BANCO)
        ON DELETE NO ACTION
        ON UPDATE CASCADE
);