---FUNCION PARA FECHA ALEATORIA


CREATE VIEW seeder
AS
    SELECT RAND(CONVERT(VARBINARY, NEWID())) seed
GO

CREATE FUNCTION dbo.randomFecha
(
	@lower DATE,
	@upper DATE
)
RETURNS DATETIME
AS
BEGIN
	DECLARE @random DATE
	SELECT @random = DATEADD(day, DATEDIFF(DAY, @lower, @upper) * seed, @lower) FROM dbo.seeder
	RETURN CONVERT(DATETIME, @random)
END

---FECHAS RANDOM EN 2019
SELECT dbo.randomFecha ('2019-01-01', '2019-12-31');


---INSERCION 

SET NOCOUNT ON;
DECLARE @Counter INT =0;
WHILE @Counter < 100 BEGIN
	INSERT INTO RESERVACION
		VALUES (dbo.randomFecha ('2019-01-01', '2019-12-31'), 0,'72429333',1,'12345' );
	SET @Counter +=1;
END


SET NOCOUNT ON;
DECLARE @Counter INT =0;
WHILE @Counter < 100 BEGIN
	INSERT INTO FACTURA
		VALUES (dbo.randomFecha ('2019-01-01', '2019-12-31'), 100.00,18,' ',1,'12345' );
	SET @Counter +=1;
END


---COMPROBAR RESULTADOS

SELECT FECHA_RESERVACION,  $partition.FP_RESERVACION(FECHA_RESERVACION)
AS particion FROM RESERVACION;


SELECT FECHA_FACTURA,  $partition.FP_FACTURA(FECHA_FACTURA)
AS particion FROM FACTURA;


---CAMBIAN ARCHIVOS A SOLO LECTURA

USE master
GO

ALTER DATABASE RESTAURANTE_BD MODIFY FILEGROUP reservacion_1 READ_WRITE;
ALTER DATABASE RESTAURANTE_BD MODIFY FILEGROUP orden_1 READ_ONLY;
ALTER DATABASE RESTAURANTE_BD MODIFY FILEGROUP factura_1 READ_ONLY;

ALTER DATABASE RESTAURANTE_BD MODIFY FILEGROUP factura_1 READ_WRITE;
ALTER DATABASE RESTAURANTE_BD MODIFY FILEGROUP reservacion_1 READ_WRITE;
ALTER DATABASE RESTAURANTE_BD MODIFY FILEGROUP orden_1 READ_WRITE;

USE RESTAURANTE_BD
GO
SELECT name, is_default, is_read_only FROM sys.filegroups
GO

