
CREATE PROCEDURE SP_InsertarCargo(
@nidCargo VARCHAR(3),
@nCargo VARCHAR(45))
AS
BEGIN
	INSERT INTO CARGO(ID_CARGO, NOMBRE_CARGO) 
	VALUES(@nidCargo, @nCargo)
END


-----------------------

CREATE PROCEDURE SP_InsertarSucursal(
@idsuc VARCHAR(3),
@nombre VARCHAR(45),
@direc VARCHAR(100),
@telf INT,
@saldo NUMERIC(10,2),
@idsucargo VARCHAR(3)
)
AS 
BEGIN 
	INSERT INTO SUCURSAL(ID_SUCURSAL, NOMBRE_SUCURSAL, DIRECCION, TELEFONO_SUCURSAL, SALDO, ID_SUCURSAL_CARGO)
	VALUES(@idsuc,@nombre,@direc,@telf,@saldo,@idsucargo)
END


---------------------

CREATE PROCEDURE SP_InsertarEmpleado(
@DNI VARCHAR(8),
@nom VARCHAR(45),
@ape VARCHAR(45),
@dire VARCHAR(100),
@telf INT,
@nac DATETIME,
@cor VARCHAR(45),
@sal NUMERIC(6,2),
@idsuc VARCHAR(3),
@idcar VARCHAR(3)
)
AS 
BEGIN
	INSERT INTO EMPLEADO(ID_EMPLEADO, NOMBRES_EMPLEADO, APELLIDOS_EMPLEADO, DIRECCION, TELEFONO_EMPLEADO, NACIMIENTO, CORREO, SALARIO, ID_SUCURSAL, ID_CARGO)
	VALUES(@DNI,@nom,@ape,@dire,@telf,@nac,@cor,@sal,@idsuc,@idcar)
END


-----------


CREATE PROCEDURE SP_Registro_HoraEntrada(
@idempl VARCHAR(8)
)
AS
BEGIN 
	INSERT INTO REGISTRO_JORNADA(HORA_ENTRADA,ID_EMPLEADO)
	VALUES (CONVERT(DATETIME, GETDATE() ),@idempl)
END