
CREATE PROCEDURE SP_InsertarCargo(
@nidCargo VARCHAR(3),
@nCargo VARCHAR(45))
AS
BEGIN
	INSERT INTO CARGO(ID_CARGO, NOMBRE_CARGO) 
	VALUES(@nidCargo, @nCargo)
END


-----------------------

CREATE PROCEDURE SP_InsertarSucursal(
@idsuc VARCHAR(3),
@nombre VARCHAR(45),
@direc VARCHAR(100),
@telf INT,
@saldo NUMERIC(10,2),
@idsucargo VARCHAR(3)
)
AS 
BEGIN 
	INSERT INTO SUCURSAL(ID_SUCURSAL, NOMBRE_SUCURSAL, DIRECCION, TELEFONO_SUCURSAL, SALDO, ID_SUCURSAL_CARGO)
	VALUES(@idsuc,@nombre,@direc,@telf,@saldo,@idsucargo)
END


---------------------

CREATE PROCEDURE SP_InsertarEmpleado(
@DNI VARCHAR(8),
@nom VARCHAR(45),
@ape VARCHAR(45),
@dire VARCHAR(100),
@telf INT,
@nac DATETIME,
@cor VARCHAR(45),
@sal NUMERIC(6,2),
@idsuc VARCHAR(3),
@idcar VARCHAR(3)
)
AS 
BEGIN
	INSERT INTO EMPLEADO(ID_EMPLEADO, NOMBRES_EMPLEADO, APELLIDOS_EMPLEADO, DIRECCION, TELEFONO_EMPLEADO, NACIMIENTO, CORREO, SALARIO, ID_SUCURSAL, ID_CARGO)
	VALUES(@DNI,@nom,@ape,@dire,@telf,@nac,@cor,@sal,@idsuc,@idcar)
END


-----------


CREATE PROCEDURE SP_Registro_HoraEntrada(
@idempl VARCHAR(8)
)
AS
BEGIN 
	INSERT INTO REGISTRO_JORNADA(HORA_ENTRADA,ID_EMPLEADO)
	VALUES (CONVERT(DATETIME, GETDATE() ),@idempl)
END

------------

CREATE PROCEDURE SP_Registro_HoraSalida(
@idempl VARCHAR(8)
)
AS
BEGIN 
	UPDATE REGISTRO_JORNADA
	SET HORA_SALIDA = CONVERT(DATETIME, GETDATE())
	WHERE ID_EMPLEADO=@idempl
END


-----------

CREATE PROCEDURE SP_InsertarMesa(
@idmesa VARCHAR(3),
@capa INT,
@idsuur VARCHAR(3)
)
AS 
BEGIN 
	INSERT INTO MESA(ID_MESA,CAPACIDAD, ID_SUCURSAL)
	VALUES (@idmesa,@capa,@idsuur)
END


--------

CREATE PROCEDURE SP_InsertarProveedor(
@idprov VARCHAR(3),
@nomprov VARCHAR(45),
@nomemp VARCHAR(45),
@telf INT
)
AS 
BEGIN 
	INSERT INTO  PROVEEDOR(ID_PROVEEDOR,NOMBRE_PROVEEDOR,NOMBRE_EMPRESA,TELEFONO_PROVEEDOR)
	VALUES (@idprov,@nomprov,@nomemp,@telf)
END


--------

CREATE PROCEDURE SP_InsertarTipoInsumo(
@idtipo VARCHAR(3),
@nombretipo VARCHAR(45))
AS
BEGIN
	INSERT INTO TIPO_INSUMO(ID_TIPO_INSUMO, NOMBRE_TIPO_INSUMO) 
	VALUES(@idtipo, @nombretipo)
END

--------

CREATE PROCEDURE SP_InsertarInsumo(
@idinsumo VARCHAR(3),
@nombre VARCHAR(45),
@marca VARCHAR(45),
@idprov VARCHAR(3),
@idtipoin VARCHAR(3)
)
AS
BEGIN
	INSERT INTO INSUMO(ID_INSUMO,NOMBRE_INSUMO,MARCA,ID_PROVEEDOR,ID_TIPO_INSUMO)
	VALUES (@idinsumo,@nombre,@marca,@idprov,@idtipoin)
END


--------------------



CREATE PROCEDURE SP_InsertarPedido(
@cant_ped INT,
@obv  VARCHAR(45),
@pre_ins NUMERIC(6,2),
@cant_ins INT,
@med_ins VARCHAR(5),
@idsucur VARCHAR(3),
@idins VARCHAR(3)
)
AS
BEGIN
	INSERT INTO PEDIDO(FECHA_PEDIDO,CANTIDAD_PEDIDO,OBSERVACIONES,PRECIO_INSUMO,CANTIDAD_INSUMO,MEDIDA_INSUMO,ID_SUCURSAL,ID_INSUMO)
	VALUES (  @cant_ped,@obv,@pre_ins,@cant_ins,@med_ins,@idsucur,@idins)
END


-----------


CREATE PROCEDURE SP_InsertarSeccion(
@nom VARCHAR(45)
)
AS
BEGIN
	INSERT INTO SECCION(NOMBRE_SECCION)
	VALUES (@nom)
END


-----------


CREATE PROCEDURE SP_InsertarCategoria(
@nom VARCHAR(45),
@idsec INT
)
AS
BEGIN
	INSERT INTO CATEGORIA(NOMBRE_CATEGORIA,ID_SECCION)
	VALUES (@nom,@idsec)
END


-------


CREATE PROCEDURE SP_InsertarProducto(
@nom VARCHAR(45),
@prec NUMERIC(5,2),
@desc VARCHAR(100),
@idcat INT
)
AS
BEGIN
	INSERT INTO PRODUCTO (NOMBRE_PRODUCTO,PRECIO_PRODUCTO,DESCRIPCION,ID_CATEGORIA)
	VALUES (@nom,@prec,@desc,@idcat)
END


-------

CREATE PROCEDURE SP_InsertarOrden(
@idmesa VARCHAR(3),
@idemp VARCHAR(8),
@idsucur VARCHAR(3)
)
AS
BEGIN
	INSERT INTO ORDEN(ID_MESA,ID_EMPLEADO,ID_SUCURSAL)
	VALUES (@idmesa,@idemp,@idsucur)
END


---------


CREATE PROCEDURE SP_InsertarOrden_Producto(
@cant INT,
@idor INT,
@idpro INT
)
AS
BEGIN
	INSERT INTO ORD_PROD(CANTIDAD_PROD,ID_ORDEN,ID_PRODUCTO)
	VALUES (@cant,@idor,@idpro)
END


--------

CREATE PROCEDURE SP_InsertarCliente(
@nom VARCHAR(45),
@ape VARCHAR(45),
@telf INT
)
AS
BEGIN
	INSERT INTO CLIENTE(NOMBRES_CLIENTE,APELLIDOS_CLIENTE,TELEFONO_CLIENTE)
	VALUES (@nom,@ape,@telf)
END



------------


CREATE PROCEDURE SP_InsertarReservacion(
@fecha DATETIME,
@idcli INT,
@idmes VARCHAR(3),
@idsuc VARCHAR(3)
) 
AS
BEGIN
	INSERT INTO RESERVACION(FECHA_RESERVACION,ID_CLIENTE,ID_MESA,ID_SUCURSAL)
	VALUES (@fecha,@idcli,@idmes,@idsuc)
END


------

CREATE PROCEDURE SP_InsertarBancos(
@nom VARCHAR(45)
) 
AS
BEGIN
	INSERT INTO BANCO(NOMBRE_BANCO)
	VALUES (@nom)
END


---------------

CREATE PROCEDURE SP_InsertarFactura(
@total NUMERIC(10,2),
@igv INT,
@formp VARCHAR(45),
@idord INT,
@idsuc VARCHAR(3)
)
AS
BEGIN
	INSERT INTO FACTURA(FECHA_FACTURA,TOTAL,IGV,FORMA_PAGO,ID_ORDEN,ID_SUCURSAL)
	VALUES (CONVERT(DATETIME, GETDATE()),@total,@igv,@formp,@idord,@idsuc )
END



-----------

CREATE PROCEDURE SP_InsertarTransaccion(
@numero INT,
@moneda VARCHAR(45),
@idbanco INT,
@idfac INT
) 
AS
BEGIN
	INSERT INTO TRANSACCION(NUMERO_TRANS,MONEDA,ID_BANCO,ID_FACTURA)
	VALUES (@numero,@moneda,@idbanco,@idfac)
END





























